- name: Set variable for /admin_tools/eda_awx_install_config directory
  stat:
    path: "/admin_tools/eda_awx_install_config"
  register:  admin_tools_eda_awx_install_dir_check

- name: Create the ITS_tools directory if it is not present
  ansible.builtin.file:
    path: "/admin_tools/eda_awx_install_config"
    state: directory
    mode: '0755'
    recurse: yes
  when: not admin_tools_eda_awx_install_dir_check.stat.exists == true
  



- name: Copy Over Custom eda-deploy files to /admin_tools/awx-operator
  ansible.builtin.copy:
    src: "{{ role_path }}/files/eda-deploy"
    dest: "/admin_tools/eda_awx_install_config"
  

- name: "Entering  hostname {{ ansible_aap_controller  }} Into secret File"
  replace:
    path: "/admin_tools/eda_awx_install_config/eda-deploy/eda.yaml"
    regexp: 'ansible_aap_controller '
    replace: "{{  ansible_aap_controller  }}"

