---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-13-volume
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  storageClassName: awx-postgres-volume
  hostPath:
    path: /var/lib/awx/postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  storageClassName: awx-projects-volume
  hostPath:
    path: /var/lib/awx/projects

