---
apiVersion: v1
kind: Secret
metadata:
  name: "awx_admin_username"
  namespace: awx
stringData:
  password: "awx_admin_username_password"
type: Opaque

---
apiVersion: v1
data:
  tls.crt: SSL_CERT
  tls.key: SSL_KEY
kind: Secret
metadata:
  creationTimestamp: null
  name: awx-secret-tls
  namespace: awx
type: kubernetes.io/tls


---
apiVersion: v1
kind: Secret
metadata:
  name: custom-awx-secret-key
  namespace: awx
stringData:
  secret_key: "super_secure_secretkey"

